config/routes.rb
Rails.application.routes.draw do
  root  'home#index'

  resources :secret_codes, only: [:index, :new, :create, :destroy]

  # devise_for :users
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/secret_codes_controller.rb
class SecretCodesController < ApplicationController

  authorize_resource :class => SecretCodesController 

  def index
    @secret_codes = Code.includes(:user).paginate(page: params[:page])
  end

  def create
    code_number = secret_params[:code_number]
    message = Code.generate_code(code_number)
    flash[:notice] = message
    redirect_to secret_codes_path
  end

  def new
    @code = Code.new
  end

  def destroy
    @code = Code.find(params[:id])
    if @code.destroy
      flash[:notice] = 'Deleted Successfully'
      redirect_to secret_codes_path
    else
      render 'new'
    end
  end

  private

  def secret_params
    params.require(:code).permit(:code_number)
  end

end

app/helpers/secret_codes_helper.rb
module SecretCodesHelper
end

app/views/secret_codes/_code.html.erb
<%= link_to 'New Secret Code', new_secret_code_path, class: 'btn btn-primary pull-right' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Code</th>
      <th>User</th>
      <th>Availibility</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @secret_codes.each do |secret_code| %>
      <tr>
        <td><%= secret_code.code %></td>
        <td><%= full_name(secret_code.user) %></td>
        <td>
          <% if secret_code.user.present? %>
          <p class="text-primary">Unavailable</p>
          <% else %>
          <p class="text-success">Available</p>
          <% end %>
        </td>
        <td>
          <%= link_to 'Destroy', secret_code_path(secret_code.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Secret Code', new_secret_code_path, class: 'btn btn-primary pull-right' %>

app/views/secret_codes/index.html.erb
  <h2>Secret Codes</h2>
  <%= will_paginate(@secret_codes) %>

  <ul class="secret_codes">
    <%= render 'code'  %>    
  </ul>
  <%= will_paginate(@secret_codes) %>

app/views/secret_codes/new.html.erb
<h2>Generate New Codes</h2>
<div class="row">
  <div class="col-md-3 col-md-offset-3">
	<%= form_for(@code, url: secret_codes_path, html: { method: :post }) do |f| %>

    <%= f.label :code_number %>&nbsp;&nbsp;(How many ? )<br/>
    <%= select_tag 'code[code_number]', options_for_select([1,10,20,50,100]), {class: 'form-control'} %>

    <%= f.submit "Generate codes", class: 'btn btn-primary' %>
	<% end %>
	</div>
</div>